services:
  ros-workshop:
    image: ros-workshop
    container_name: ros-workshop-dev
    network_mode: host
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    runtime: nvidia
    volumes:
      - ./src:/ros_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, display, graphics]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=0
